services:
  app:
    image: ghcr.io/indiemap-uk/indiemap:latest
    environment:
      - ADMIN_USER_EMAILS
      - AUTH_RESEND_KEY
      - AUTH_SECRET
      - DATABASE_URL=postgresql://indie:indie@postgresql:5432/indie?sslmode=disable
      - GEOCODIFY_API_KEY
      - JINA_API_KEY
      - OPENAI_API_KEY
    ports:
      - "3333:3333"
    restart: unless-stopped
    depends_on:
      - postgresql
  postgresql:
    image: docker.io/bitnami/postgresql:17
    hostname: postgresql
    ports:
      - "5431:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_DATABASE=indie
      - POSTGRESQL_USERNAME=indie
      - POSTGRESQL_PASSWORD=indie

volumes:
  postgresql_data:
    driver: local
