export const ukCounties = [
  'Aberdeenshire',
  'Angus',
  'Argyll and Bute',
  'Ayrshire and Arran',
  'Banffshire',
  'Bedfordshire',
  'Berkshire',
  'Berwickshire',
  'Bristol',
  'Buckinghamshire',
  'Caithness',
  'Cambridgeshire',
  'Cheshire',
  'City of Aberdeen',
  'City of Dundee',
  'City of Edinburgh',
  'City of Glasgow',
  'Clackmannan',
  'Clwyd',
  'Cornwall',
  'County Antrim',
  'County Armagh',
  'County Derry / Londonderry',
  'County Down',
  'County Fermanagh',
  'County Tyrone',
  'Cumbria',
  'Derbyshire',
  'Devon',
  'Dorset',
  'Dumfries',
  'Dunbartonshire',
  'Durham',
  'Dyfed',
  'East Lothian',
  'East Riding of Yorkshire',
  'East Sussex',
  'Essex',
  'Fife',
  'Gloucestershire',
  'Greater London',
  'Greater Manchester',
  'Gwent',
  'Gwynedd',
  'Hampshire',
  'Herefordshire',
  'Hertfordshire',
  'Inverness',
  'Isle of Man',
  'Isle of Wight',
  'Kent',
  'Kincardineshire',
  'Lanarkshire',
  'Lancashire',
  'Leicestershire',
  'Lincolnshire',
  'Merseyside',
  'Mid Glamorgan',
  'Midlothian',
  'Moray',
  'Nairn',
  'Norfolk',
  'North Yorkshire',
  'Northamptonshire',
  'Northumberland',
  'Nottinghamshire',
  'Orkney',
  'Oxfordshire',
  'Perth and Kinross',
  'Powys',
  'Renfrewshire',
  'Ross and Cromarty',
  'Roxburgh, Ettrick and Lauderdale',
  'Rutland',
  'Shetland',
  'Shropshire',
  'Somerset',
  'South Glamorgan',
  'South Yorkshire',
  'Staffordshire',
  'Stirling and Falkirk',
  'Suffolk',
  'Surrey',
  'Sutherland',
  'The Stewartry of Kirkcudbright',
  'Tweeddale',
  'Tyne and Wear',
  'Warwickshire',
  'West Glamorgan',
  'West Lothian',
  'West Midlands',
  'West Sussex',
  'West Yorkshire',
  'Western Isles',
  'Wigtown',
  'Wiltshire',
  'Worcestershire',
]
