services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    hostname: postgresql
    ports:
      - '5431:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=indie
      - POSTGRESQL_USERNAME=indie
      - POSTGRESQL_PASSWORD=indie

volumes:
  postgresql_data:
    driver: local
