name: Docker Image CI
description: Build and push Docker image then trigger a deploy

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/indiemap-uk/indiemap:latest -t ghcr.io/indiemap-uk/indiemap:${GITHUB_SHA} --file workloads/web/Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/indiemap-uk/indiemap:${GITHUB_SHA}
          docker push ghcr.io/indiemap-uk/indiemap:latest
      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
