name: Migrate Database

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/repository/migrations/*'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --prefer-offline -F repository...

      - name: Run database migrations
        run: pnpm -F repository mig:up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
